# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: gradzcircle.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
    client:
        service-url:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource        
        #url: ${JDBC_DATABASE_URL}
        #username: ${JDBC_DATABASE_USERNAME}
        #password: ${JDBC_DATABASE_PASSWORD}
        url: jdbc:postgresql://ec2-174-129-22-84.compute-1.amazonaws.com:5432/ddsk6kjocpbd3r
        username: xllxrjezvwzgnf
        password: c080edbf5c5e3de2ec9879297c1602dfde9f1572f94db12a74e9dac5e516733d
        hikari:
            maximumPoolSize: 8
