version: '2'
services:
    gradzcircle-app:
        image: gradzcircle
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gradzcircle-postgresql:5432/gradzcircle
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gradzcircle-elasticsearch:9300
        ports:
            - 8080:8080
    gradzcircle-postgresql:
        extends:
            file: postgresql.yml
            service: gradzcircle-postgresql
    gradzcircle-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gradzcircle-elasticsearch
