INSERT INTO college (id, college_name,domain_name,university_id, status) VALUES
  (1, 'National University of Singapore','nus.edu.sg', 1, 1),
  (2, 'Nanyang Technological University','ntu.edu.sg', 2, 1),
  (3, 'Singapore Management University','smu.edu.sg', 3, 1),
  (4, 'Singapore University of Technology and Design','sutd.edu.sg',4, 1),
  (5, 'Singapore Institute of Technology','singaporetech.edu.sg', 5, 1),
  (6, 'SIM University','unisim.edu.sg', 6, 1),
  (7, 'National Institute of Education','nie.edu.sg', 2, 1),
  (8, 'Lee Kuan Yew School of Public Policy','nus.edu.sg', 1, 1),
  (9, 'Duke-NUS Graduate Medical School','TBD-Abhinav', 1, 1),
  (10, 'S. Rajaratnam School of International Studies','ntu.edu.sg', 2, 1),
  (11, 'Yale-NUS College','yale-nus.edu.sg', 1, 1),
  (12, 'German Institute of Science and Technology','tum-asia.edu.sg', 1, 1),
  (13, 'Singapore Polytechnic','sp.edu.sg', 7, 1),
  (14, 'Ngee Ann Polytechnic','np.edu.sg', 8, 1),
  (15, 'Temasek Polytechnic','tp.edu.sg', 9, 1),
  (16, 'Nanyang Polytechnic','nyp.edu.sg', 10, 1),
  (17, 'Republic Polytechnic','rp.edu.sg ', 11, 1),
  (18, 'Nanyang Academy of Fine Arts', 'nafa.edu.sg',12, 1),
  (19, 'LASALLE College of the Arts', 'lasalle.edu.sg',13, 1),
  (20, 'M.A.D. School', 'cma-academy.com',14, 1),
  (21, 'James Cook University Singapore','jcu.edu.au', 17, 1),
  (22, 'ESSEC Business School', 'essec.edu',18, 1),
  (23, 'Embry-Riddle Aeronautical University','erau.edu', 19, 1),
  (24, 'Rutgers Business School Asia Pacific','rutgers.edu.sg', 20, 1),
  (25, 'University of Nevada Las Vegas Singapore', 'unlv.edu.sg',21, 1),
  (26, 'Curtin University Singapore','curtin.edu.sg', 22, 1),
  (27, 'Ngee Ann - Adelaide Education Centre Pte Ltd','NAA.edu.sg', 23, 1),
  (28, 'Temple University, Singapore','erci.edu.sg', 24, 1),
  (29, 'Cardiff Metropolitan University: Asia Campus', 'easb.edu.sg',25, 1),
  (30, 'Queen Margaret University, Edinburgh: Asia Campus','easb.edu.sg', 26, 1),
  (31, 'INSEAD', 'insead.edu',27, 1),
  (32, 'S P Jain School of Global Management, Singapore Campus','spjain.org', 28, 1),
  (33, 'James Lind Institute','jli.sg', 29, 1),
  (34, 'DigiPen Institute of Technology Singapore','digipen.edu', 30, 1),
  (35, 'St. Gallen Institute of Management in Asia','unisg.ch', 31, 1),
  (36, 'Singapore Raffles Music College','srmc.edu.sg', 15, 1),
  (37, 'CG Protege Animation School','cgprotege.com', 16, 1),
  (38, 'Singapore Polytechnic: Massey University','sp.edu.sg',34, 1),
  (39, 'Ngee Ann Polytechnic: Chapman University','np.edu.sg',35, 1),
  (40, 'Nanyang Polytechnic : University of Stirling','nyp.edu.sg',36 , 1),
  (41, 'Stansfield College','stansfield.edu.sg', 37, 1),
  (42, 'Asia Pacific Centre for Management Leadership', 'TODO-abhinav',38, 1),
  (43, 'Auston Institute', 'auston.edu.sg',39, 1),
  (44, 'BMC International College','bmc.edu.sg', 40, 1),
  (45, 'EASB East Asia Institute of Management', 'easb.edu.sg',41, 1),
  (46, 'ERC Institute','erci.edu.sg', 42, 1),
  (47, 'Informatics Academy', 'informatics.edu.sg', 43, 1),
  (48, 'Johns Hopkins in Singapore', 'Division of Biomedical Sciences', 44, 1),
  (49, 'Kaplan Singapore', 'kaplan.com', 45, 1),
  (50, 'Marketing Institute of Singapore','mis.edu.sg', 46, 1),
  (51, 'Management Development Institute of Singapore','mdis.edu.sg', 47, 1),
  (52, 'PSB Academy','psb-academy.edu.sg', 48, 1),
  (53, 'Singapore Institute of Management','sim.edu.sg', 49, 1),
  (54, 'TMC Academy', 'tmc.edu.sg',50, 1),
  (55,'DIMENSIONS International College','dimensions.edu.sg', 51, 1),
  (56, 'Melior International College','mic.edu.sg', 52, 1),
  (57, 'Others','others', 53, 1);
