INSERT INTO industry(id,industry_name)VALUES
(1,'Accounting / Auditing / Taxation'),
(2,'Admin / Secretarial'),
(3,'Advertising / Media'),
(4,'Aerospace Engineering'),
(5,'Architecture / InteriorDesign'),
(6,'Automotive'),
(7,'Banking and Finance'),
(8,'Biotechnology'),
(9,'Building and Construction'),
(10,'Chemicals'),
(11,'Consulting'),
(12,'Consumer Business'),
(13,'Customer Service'),
(14,'Defence'),
(15,'Design'),
(16,'Education and Training'),
(17,'Electronics'),
(18,'Energy'),
(19,'Engineering'),
(20,'Entertainment / Media / Broadcasting'),
(21,'Environment / Health'),
(22,'Events / Promotions'),
(23,'F&B'),
(24,'General Management'),
(25,'General Work'),
(26,'Healthcare / Pharmaceutical'),
(27,'Hospitality'),
(28,'Human Resources'),
(29,'Infocomm Products'),
(30,'Infocomm Services'),
(31,'Information Technology'),
(32,'Insurance'),
(33,'International Non-Profit Organizations'),
(34,'Legal'),
(35,'Logistics / Supply Chain'),
(36,'Manufacturing'),
(37,'Marketing / Public Relations'),
(38,'Medical / Therapy Services'),
(39,'Medical Technology'),
(40,'Natural Resources'),
(41,'Oil and Gas'),
(42,'Personal Care / Beauty'),
(43,'Professional Services'),
(44,'Public / Civil Service'),
(45,'Purchasing / Merchandising'),
(46,'RealEstate / Property Management'),
(47,'Repair and Maintenance'),
(48,'Risk Management'),
(49,'Sales / Retail'),
(50,'Sciences / Laboratory / R&D'),
(51,'Security and Investigation'),
(52,'Social Services'),
(53,'Space'),
(54,'Sports'),
(55,'Telecommunications'),
(56,'Travel / Tourism'),
(57,'Others');
