INSERT INTO job_category (id, job_category) VALUES
(1,'Accounting'),
(2,'General Business'),
(3,'Admin & Clerical'),
(4,'General Labor'),
(5,'Pharmaceutical'),
(6,'Automotive'),
(7,'Government'),
(8,'Professional Services'),
(9,'Banking'),
(10,'Grocery'),
(11,'Purchasing - Procurement'),
(12,'Biotech'),
(13,'Health Care'),
(14,'QA - Quality Control'),
(15,'Broadcast - Journalism'),
(16,'Hotel - Hospitality'),
(17,'Real Estate'),
(18,'Business Development'),
(19,'Human Resources'),
(20,'Research'),
(21,'Construction'),
(22,'Information Technology'),
(23,'Restaurant - Food Service'),
(24,'Consultant'),
(25,'Installation - Maint - Repair'),
(26,'Retail'),
(27,'Customer Service'),
(28,'Insurance'),
(29,'Sales'),
(30,'Design'),
(31,'Inventory'),
(32,'Science'),
(33,'Distribution - Shipping'),
(34,'Legal'),
(35,'Skilled Labor - Trades'),
(36,'Education - Teaching'),
(37,'Legal Admin'),
(38,'Strategy - Planning'),
(39,'Engineering'),
(40,'Management'),
(41,'Supply Chain'),
(42,'Entry Level - New Grad'),
(43,'Manufacturing'),
(44,'Telecommunications'),
(45,'Executive'),
(46,'Marketing'),
(47,'Training'),
(48,'Facilities'),
(49,'Media - Journalism - Newspaper'),
(50,'Transportation'),
(51,'Finance'),
(52,'Nonprofit - Social Services'),
(53,'Warehouse'),
(54,'Franchise'),
(55,'Nurse'),
(56,'Other'),
(57,'Oilfield Services'),
(58,'Drilling/Rig'),
(59,'Health, Safety & Env');
