 INSERT INTO qualification (id, qualification,weightage,category) VALUES
(1, 'B.E/B.Tech',3,'Engg'),
(2, 'MBA/PGDM',4,'Business Studies'),
(3, 'MCA',4,'Computer'),
(4, 'M.E/ M.Tech',4,'Engg'),
(5, 'M.Sc',4,'Science'),
(6, 'B.Arch',3,'Architecture'),
(7, 'B.Com',3,'Commerce'),
(8, 'B.Pharm',3,'Pharmacy'),
(9, 'B.A.',3,'Arts'),
(10, 'BBA/BBM',3,'Business Studies'),
(11, 'BCA',3,'Computer'),
(12, 'BDS',3,'Dental'),
(13, 'B.Ed',3,'Education'),
(14, 'BHM',3,'Hotel Mgmt'),
(15, 'B.Sc',3,'Science'),
(16, 'C.A',-1,'Accountancy'),
(17, 'CS',-1,'Computer Science'),
(18, 'ICWA',-1,''),
(19, 'LLB',-1,'Law'),
(20, 'MBBS',4,'Medicine'),
(21, 'B.Design',3,'Fashion'),
(22, 'B.FashionTech',3,'Fashion'),
(23, 'BFA',3,'FIne Arts'),
(24, 'BAMS',3,'Ayurveda'),
(25, 'BHMS',3,'Homeopathy'),
(26, 'B.P.Ed',3,'PE'),
(27, 'B.F.Sc',3,'Fisheries'),
(28, 'BSW',3,'Social Work'),
(29, 'Other',-1,'Default'),
(30, 'No Formal Qualification',0,'Default'),
(31,'Certificate Course ITI',1),
(32, 'Diploma',2,'Diploma'),
(33, 'M.Chirurgiae',4,'Surgery'),
(34, 'M.F.Sc',4,'Fisheries'),
(35, 'MPEd',4,'PE'),
(36, 'MVSc',4,'Veterinary'),
(37, 'P.G.Diploma',4,'Diploma'),
(38, 'MSW',4,'Social Work'),
(39, 'MS',4,'Surgery'),
(40, 'MHM',4,'Hotel Mgmt'),
(41, 'M.Ed',4,'Education'),
(42, 'MDS',4,'Dental'),
(44, 'MA',4,'Arts'),
(45, 'M.Pharm',4,'Pharmacy'),
(46, 'M.Arch',4,'Architecture'),
(47, 'M.Phil/PhD',5,'Phd'),
(48, 'LLM',-1,'Law'),
(49,'B.Sc Pharmacy',3,'Pharmacy'),
(50,'BBS - Bachelor of Business Studies',3,'Business Studies'),
(51,'BMS - Bachelor in Management Studies',3,'Business Studies'),
(52,'LT - Licentiate in Teaching',3,'Education'),
(53,'BHMCT - Bachelor of Hotel Management and Catering Technology',3,'Hotel Mgmt'),
(54,'Bachelor of Accountancy',-1,'Accountancy'),
(55,'Master of Surgery',4,'Surgery')
(56,'PHD',4,'Phd')
(57,'Doctrate',4,'Phd');