INSERT INTO qualification (id, qualification) VALUES
(1, 'Doctorate'),
(2, 'Master'),
(3, 'Postgraduate Diploma or equivalent'),
(4, 'WSQ Graduate Certificate'),
(5, 'WSQ Graduate Diploma'),
(6, 'Bachelor Degree'),
(7, 'Polytechnic Diploma'),
(8, 'ITE Diploma, WSQ Diploma, Career Readiness Certificate (Managerial Level) or equivalent'),
(9, 'Professional Certifications'),
(10, 'GCE ''''A'''' Level'),
(11, 'Higher Nitec'),
(12, 'Nitec, Certificate in Office Skills, NTC Grade 2 or equivalent'),
(13, 'WSQ Advanced Certificate, Career Readiness Certificate (Supervisory Level)'),
(14, 'WSQ Higher Certificate'),
(15, 'WSQ Certificate, Career Readiness Certificate (Operations Level)'),
(16, 'GCE ''O'' Level'),
(17, 'Nitec (Intermediate)  /  Certificate of Vocational Training  /  NTC Grade 3 or equivalent'),
(18, 'ISC, CoC or equivalent'),
(19, 'ESS WPLN 5 and above'),
(20, 'GCE ''N'' Level'),
(21, 'Secondary Education'),
(22, 'Basic Vocational Certificate'),
(23, 'WISE 1-3'),
(24, 'ESS WPLN 3-4'),
(25, 'PSLE  /  PSPE'),
(26, 'Primary Education'),
(27, 'ESS WPLN 1-2'),
(28, 'BEST'),
(29, 'Other'),
(30, 'No Formal Qualification');
