INSERT INTO Skills (id, skill) VALUES
(1, 'PHP, HTML, CSS, Jquery, Ajax and Javascipt'),
(2, 'Accounting'),
(3, 'Adobe Flash'),
(4, 'Adobe Illustrator'),
(5, 'Adobe Image Styler'),
(6, 'Adobe Photo Shop'),
(7, 'Adobe Photoshop'),
(8, 'Adobe Premier'),
(9, 'Adove Captivate'),
(10, 'Advertising'),
(11, 'Android/ iOS Application Developer'),
(12, 'Animation'),
(13, 'Animation Shop'),
(14, 'Art'),
(15, 'Auditing'),
(16, 'Auto CAD'),
(17, 'Basic Entrepreneurial Skills'),
(18, 'Basic HTML, CMS and Flash knowledge'),
(19, 'Biology'),
(20, 'Blogger'),
(21, 'Business Skills'),
(22, 'Camera work'),
(23, 'Camtasia'),
(24, 'Communication Skills'),
(25, 'Communication skills, presentation skiils'),
(26, 'Computer Hardware  &  Networking'),
(27, 'Computer Programming Skills'),
(28, 'Computer Science'),
(29, 'Concept Marketing'),
(30, 'Content Writing'),
(31, 'Content Writing/Editorial'),
(32, 'Copy-writing'),
(33, 'Coral Draw'),
(34, 'Corporate Proposal and Formal Communication'),
(35, 'Counselling  &  Guidance'),
(36, 'Creative Thinking'),
(37, 'Database Management'),
(38, 'Digital Marketing'),
(39, 'E-commerce'),
(40, 'Economic Research  &  Forecasting'),
(41, 'Entrepreneurial'),
(42, 'Ethical Hacking'),
(43, 'Event Management'),
(44, 'Financial Management/Analysis'),
(45, 'Fund Raising'),
(46, 'GIF animations'),
(47, 'Good Understanding of Brands and Creative Writing Skills'),
(48, 'Graphic Designing Skills'),
(49, 'Hotel  &  Restaurant Management'),
(50, 'HR Management'),
(51, 'HTML Coding'),
(52, 'HTML5 + CSS 3 Knowledge'),
(53, 'Image Editing'),
(54, 'Import  &  Export'),
(55, 'Intellectual Property Rights'),
(56, 'Interaction Design'),
(57, 'Interest in E-Commerce'),
(58, 'Interior Designing, Architecture'),
(59, 'Internet'),
(60, 'Journalism'),
(61, 'JSP, ASP, JAVA'),
(62, 'Law  &  Business Law'),
(63, 'Leadership Skills'),
(64, 'Mac OS'),
(65, 'Marketing '),
(66, 'Mathematical orientation'),
(67, 'Microsoft Office'),
(68, 'MIcrosoft Silverlight'),
(69, 'Microsoft Visio'),
(70, 'Mobile Application Development Skills'),
(71, 'MS Office Skills'),
(72, 'Negotiation Skills'),
(73, 'Network Management/Data Transmission'),
(74, 'Networking'),
(75, 'Operations.'),
(76, 'Paint Shop Pro'),
(77, 'Painter'),
(78, 'Photo Editing'),
(79, 'Photography knowledge'),
(80, 'PHP, MySQL'),
(81, 'PHP,Drupal CMS'),
(82, 'PR skills'),
(83, 'Product designing'),
(84, 'Product Planning, Brand Management'),
(85, 'Project Management'),
(86, 'Quantitative Aptitude  &  Logical Reasoning'),
(87, 'Recruitment  &  Allocation'),
(88, 'Research  &  Analysis'),
(89, 'Robotics'),
(90, 'Sales Orientation'),
(91, 'SEO'),
(92, 'Six Sigma'),
(93, 'Social Media Marketing'),
(94, 'Software Development'),
(95, 'Software Development/Programming'),
(96, 'Sound Forge 7'),
(97, 'Staffing'),
(98, 'Statistics Orientation'),
(99, 'Stock market'),
(100, 'Strategic'),
(101, 'Taxation'),
(102, 'Team Player'),
(103, 'Team Skills'),
(104, 'Technical Skills'),
(105, 'Training  &  Development'),
(106, 'Travel  &  Tourism'),
(107, 'Video Editing'),
(108, 'Web Development  &  Management'),
(109, 'Web Marketing'),
(110, 'website designing'),
(111, 'Windows OS'),
(112, 'Writing and editorial skills');
