INSERT INTO Skills (id, skill) VALUES
(1, 'PHP'),
(2, 'Accounting'),
(3, 'Adobe Flash'),
(4, 'Adobe Illustrator'),
(5, 'Adobe Image Styler'),
(6, 'Adobe Photo Shop'),
(7, 'Adobe Photoshop'),
(8, 'Adobe Premier'),
(9, 'Adobe Captivate'),
(10, 'Advertising'),
(11, 'Android Development'),
(13, 'Animation Shop'),
(14, 'Art'),
(15, 'Auditing'),
(16, 'Auto CAD'),
(17, 'Entrepreneurial Skills'),
(20, 'Blogger'),
(21, 'Business Skills'),
(22, 'Camera work'),
(23, 'Camtasia'),
(24, 'Communication Skills'),
(25, 'Presentation skiils'),
(26, 'Computer Hardware  &  Networking'),
(27, 'Computer Programming Skills'),
(29, 'Concept Marketing'),
(30, 'Content Writing'),
(32, 'Copy-writing'),
(33, 'Coral Draw'),
(35, 'Counselling  &  Guidance'),
(36, 'Creative Thinking'),
(37, 'Database Management'),
(38, 'Digital Marketing'),
(39, 'E-commerce'),
(40, 'Economic Research  &  Forecasting'),
(42, 'Ethical Hacking'),
(43, 'Event Management'),
(44, 'Financial Management/Analysis'),
(45, 'Fund Raising'),
(46, 'GIF animations'),
(48, 'Graphic Designing Skills'),
(49, 'Hotel  &  Restaurant Management'),
(50, 'HR Management'),
(53, 'Image Editing'),
(54, 'Import  &  Export'),
(55, 'Intellectual Property Rights'),
(56, 'Interaction Design'),
(57, 'Interest in E-Commerce'),
(58, 'Interior Designing'),
(59, 'Internet'),
(60, 'Journalism'),
(61, 'JAVA'),
(62, 'Law  &  Business Law'),
(63, 'Leadership Skills'),
(64, 'Mac OS'),
(65, 'Marketing'),
(67, 'Microsoft Office'),
(68, 'MIcrosoft Silverlight'),
(69, 'Microsoft Visio'),
(72, 'Negotiation Skills'),
(73, 'Network Management/Data Transmission'),
(76, 'Paint Shop Pro'),
(77, 'Painter'),
(78, 'Photo Editing'),
(79, 'Photography'),
(82, 'PR skills'),
(83, 'Product designing'),
(84, 'Brand Management'),
(85, 'Project Management'),
(86, 'Quantitative Aptitude  &  Logical Reasoning'),
(87, 'Recruitment'),
(88, 'Research  &  Analysis'),
(89, 'Robotics'),
(90, 'Sales Orientation'),
(91, 'SEO'),
(92, 'Six Sigma'),
(93, 'Social Media Marketing'),
(94, 'Software Development'),
(100, 'Strategic'),
(103, 'Team Skills'),
(105, 'Training  &  Development'),
(106, 'Travel  &  Tourism'),
(107, 'Video Editing'),
(108, 'Web Development  &  Management'),
(109, 'Web Marketing'),
(110, 'Website Designing'),
(111, 'Windows OS'),
(113, 'HTML'),
(114, 'CSS'),
(115, 'Jquery'),
(116, 'Ajax'),
(117, 'Javascipt'),
(118, 'TypeScript'),
(119, 'iOS Application Developer'),
(120, 'Angular 2+'),
(121, 'React JS'),
(122, 'Microservices'),
(123, 'Cloud Computing'),
(124, 'Github'),
(125, 'GitLab'),
(126, 'Jenkins'),
(127, 'Architecture'),
(128, 'PostgreSQL'),
(129, 'Oracle'),
(130, 'MySQL'),
(131, 'MongoDB'),
(132, 'Cassandra'),
(133, 'Angular JS');
