export const USER_ID = 'userId';
export const USER_TYPE = 'userType';
export const JOB_ID ='jobId';
export const CORPORATE_ID = 'corporateId';
export const CANDIDATE_ID = 'candidateId';
export const MATCH_SCORE = 'matchScore';
export const USER_DATA = 'userData';
export const PASSWORDVALUE = '#AyLvsktyvn1947@'
export const PASSWORDKEY = '#PshyetblskjaW1954@'
export const CANDIDATE_CERTIFICATION_ID = 'candidateCertificationId';
export const CANDIDATE_NON_ACADEMIC_ID = 'candidateNonAcademicId';
export const CANDIDATE_EDUCATION_ID = 'candidateEducationId';
export const CANDIDATE_EMPLOYMENT_ID = 'candidateEmploymentId';
export const CANDIDATE_LANGUAGE_ID = 'candidateLanguageId';
